name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@v1

      - name: Build the Docker image
        timeout-minutes: 10
        run: |
          set -x
          cd RouteAnalyzer
          docker version
          docker build -t route-analyzer .
